const REQUEST_STATUS = {
  INTERESTED: "interested",
  IGNORED: "ignored",
  ACCEPTED: "accepted",
  REJECTED: "rejected",
};

const SEND_ALLOWED_STATUS = [REQUEST_STATUS.INTERESTED, REQUEST_STATUS.IGNORED];

const REVIEW_ALLOWED_STATUS = [
  REQUEST_STATUS.ACCEPTED,
  REQUEST_STATUS.REJECTED,
];

module.exports = {
  REQUEST_STATUS,
  SEND_ALLOWED_STATUS,
  REVIEW_ALLOWED_STATUS,
};
